spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: fantastic-service1
        uri: lb://FANTASTIC1-SERVICE
        predicates:
        - Path=/fantastic/fox/**


      - id: fantastic-service2
        uri: lb://FANTASTIC2-SERVICE
        predicates:
        - Path=/ap1/v1/**


      - id: identity-service
        uri: lb://IDENTITY-SERVICE
        predicates:
        - Path=/auth/** 


server:
  port: 3333